# Generated by Django 3.2.12 on 2022-03-07 10:52

from django.db import migrations, models
import django.db.models.deletion
import bot_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=bot_app.models.image_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField()),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(null=True)),
                ('last_viewed_image', models.PositiveIntegerField(blank=True, null=True)),
                ('images_requested', models.PositiveIntegerField(default=0, verbose_name='запрошено картинок')),
            ],
        ),
        migrations.CreateModel(
            name='ImageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='кол-во голосов')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.image')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_app.user')),
            ],
        ),
    ]
